_BASE_: "Base-POLO.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 20
  POLO:
    NUM_CLASSES: 20
    NUM_MASKS: 256
    NUM_KERNELS: 256
SOLVER:
  STEPS: (15000, 45000, 135000, 200000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  GAMMA: 0.5
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5000
DATASETS:
  TRAIN: ("CIHP_train_v2",)
  TEST: ("CIHP_val_v2",)