_BASE_: "Base-POLO.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 20
  SOLOV2:
    NUM_CLASSES: 19
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("CIHP_train_v2",)
  TEST: ("CIHP_val_v2",)