_BASE_: "Base-POLO.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  POLO:
    NUM_CLASSES: 7
    NUM_MASKS: 256
    NUM_KERNELS: 256
    NORM: 'none'
    SCORE_THR: 0.5
    UPDATE_THR: 0.5
#    FPN_SCALE_RANGES: ((1, 48), (24, 96), (48, 192), (96, 384), (192, 2048))
SOLVER:
  STEPS: (70000, 100000)
  MAX_ITER: 141400
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
#  BASE_LR: 0.000003125
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
DATASETS:
  TRAIN: ("PPP_train",)
  TEST: ("PPP_val",)
TEST:
  EVAL_PERIOD: 1000
